# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoCapture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoCapture

  # Pods for ai
  pod 'TesseractOCRiOS', :git => 'https://github.com/appintheair/Tesseract-OCR-iOS'

end
